### ISSUE TITLE
 Swagger UI shows a blank page

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#10163]
### Description of the bug / feature
In a Vaadin 18 + Spring app, swagger-ui page is not showing (returns a blank page) with errors in the console.

### Minimal reproducible example

1. Create a v18 Java project from start.vaadin.com 
2. Add the dependency
```
<dependencies>
    <dependency>
   <groupId>org.springdoc</groupId>
   <artifactId>springdoc-openapi-ui</artifactId>
   <version>1.5.5</version>
</dependency>
```
3. Change Vaadin mapping to a different path using `vaadin.urlMapping` in `application.properties`. For example,
```
vaadin.url-mapping=/ui/*
```
4. Run the server, and open http://localhost:8080/swagger-ui.html

### Expected behavior
The Swagger UI page is opened
### Actual behavior
Only a blank page is displayed with the following errors in the console
![image](https://user-images.githubusercontent.com/42799254/109612678-c34e3680-7b38-11eb-963a-ead1b68e1a83.png)

### Versions:
    - Vaadin / Flow version: 18.0.6
    - Java version: 11
    - OS version: Windows

**Comment by tarekoraby** [comment]
Note, that Swagger UI seems to work fine in v14.X

**Comment by FDelporte** [comment]
Same error on 
- Java version: 15
- OS version: Mac

**Comment by denis-anisimov** [comment]
The issue is most likely a generic one even though it's technically a Spring add-on issue.

**Comment by Frettman** [comment]
It needs to be exactly `vaadin.urlMapping`. `vaadin.url-mapping` will not work, even though your IDE might suggest it. It's not a regular Spring Boot configuration property and as such it's treated a bit differently that than you might expect.

**Comment by letrthang** [comment]
I am using vaadin flow 23, Java 17, Spring boot 2.7.0 and config not work.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/13396193/173185998-7bd17965-d33d-4b1c-a1e4-68f3b40d580a.png">

**Error message:**

<img width="981" alt="image" src="https://user-images.githubusercontent.com/13396193/173186028-a3ddfecc-4a09-4a0c-b13e-6dd1c025a969.png">


I think we don't need change vaadin base URL but we need allow config to exclude swagger URL to avoid Vaadin on blocking swagger URLs.

**Comment by kochetkov-ma** [comment]
I figured it out. And it appears to be a bug, but there is a simple way to avoid it.

Vaadin version `22.0.18`
Spring Boot version `2.4.6`

I had the following `application.yaml`
```
vaadin:
  url-mapping: /web/*
```
The problem is in this code below. Specifically in the name of the setting and how to get it.
```
public class RootMappedCondition implements Condition {

    public static final String URL_MAPPING_PROPERTY = "vaadin.urlMapping";

    @Override
    public boolean matches(ConditionContext context,
            AnnotatedTypeMetadata metadata) {
        return isRootMapping(
                context.getEnvironment().getProperty(URL_MAPPING_PROPERTY));
    }
```
We have the name of the setting `"vaadin.urlMapping"`  in camelCase, and according to the `Spring Boot` specification it handles it by `Relaxed Binding` rules and for it `vaadin.url-mapping == vaadin.urlMapping`

**BUT** the way to get the setting `context.getEnvironment().getProperty(URL_MAPPING_PROPERTY)` knows nothing about these rules and only sees `vaadin.urlMapping`

To get the setting correctly, you need to get the `VaadinConfigurationProperties` bin from the context, but at this stage it is not in the context and the setting will not be resolved by `Relaxed Binding` rules from `Spring Boot`

So at this point you can easily bypass this flaw and use the configuration name `vaadin.urlMapping` in `application.yaml`.

**Comment by Artur-** [comment]
Sounds like what was fixed in https://github.com/vaadin/flow/pull/13791

**Comment by letrthang** [comment]
The issue still happens even we change **url-mapping**. It is better to fix issue #12949

**Comment by Frettman** [comment]
@letrthang, I have the same setup (based on your screenshots) and it works for me. spring/issues#602 contains some details why simply changing the orders of the URL mappings for Vaadin and Spring's resource handlers won't help.
Also, judging from your screenshot, the issue in your case is that Spring handles Vaadin's path at `/ui/`, so letting Vaadin ignore requests to certain URLs and let them pass on to Spring, wouldn't really help. Or has the error changed now?
Also, I can confirm that in the latest Vaadin version both `vaadin.urlMapping` and `vaadin.url-mapping` work now.

**Comment by letrthang** [comment]
@Frettman it still doesn't work for me. I can access restful resource using **postman** but swagger UI still doesn't show up.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/13396193/180636945-7a964a7f-1847-4065-96a1-7618f2bf6e9e.png">

<img width="381" alt="image" src="https://user-images.githubusercontent.com/13396193/180636957-e8432002-6394-45bd-808d-9b9079c731bb.png">

**Comment by Frettman** [comment]
@letrthang, that error from your first screenshot is not from Vaadin; Vaadin would show something like in the image from [this Stackoverflow question](https://stackoverflow.com/questions/71022726/vaadin-blocks-swagger-ui).
Your error looks like something from Spring, so to me it seems like you have another issue.
Have you tried accessing `/swagger-ui/index.html` directly? That's where `/swagger-ui.html` should get redirected to.

**Comment by letrthang** [comment]
@Frettman i created a test endpoint here, swagger still not work.

https://github.com/letrthang/vaadin23-flow-pro-components/blob/main/src/main/java/com/example/application/data/endpoint/TestSwaggerImpl.java

<img width="551" alt="image" src="https://user-images.githubusercontent.com/13396193/180638725-17a80444-5a87-4631-99f8-5e18ab6e8cf9.png">

**Comment by letrthang** [comment]
@tarekoraby @denis-anisimov may i know you have any plan to fix this issue ?

**Comment by tarekoraby** [comment]
@mshabarov, can someone from the Flow team please provide an update on this issue?

**Comment by Artur-** [comment]
This seems to work fine.

```
npx @vaadin/cli init swag-test
cd swag-test
# Add springdoc-openapi-ui dependency
# Add url mapping
mvn
```

opening http://localhost:4444/swagger-ui.html shows the swagger UI

**Comment by letrthang** [comment]
can someone pull my demo code to test. it is official vaadin demo code:
https://github.com/letrthang/vaadin23-flow-pro-components

**Comment by letrthang** [comment]
this config now will work with vaadin 23.2.2

```
vaadin.url-mapping=/web/*
springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html
```

However I prefer to get same config as Vaadin 14 which Vaadin home is root and allow to exclude swagger from root url: 
```
vaadin.url-mapping=/*
springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html
```

Anyway, there is other issue with open-api and Hilla:

Both springdoc-openapi-ui and Hilla using swagger-core and swagger-models with different versions, so causing swagger crashing.

**Below config will work:**

```
<properties>
        <java.version>17</java.version>
        <vaadin.version>23.2.1</vaadin.version>
        <hilla.version>1.2.1</hilla.version>
    </properties>
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.7</version>
            <!-- avoid conflict with hilla -->
            <exclusions>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-models</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 
```

**Below config will not work:**

```
<properties>
        <java.version>17</java.version>
        <vaadin.version>23.2.1</vaadin.version>
        <hilla.version>1.2.1</hilla.version>
    </properties>
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.11</version>
            <!-- avoid conflict with hilla -->
            <exclusions>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-models</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 
```

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/13396193/190431761-0babdb18-d89c-499f-b920-f3561cbb598d.png">

I submitted new issue to Hilla here:

**Comment by Artur-** [comment]
Without the root mapping it seems that the Vaadin handler is invoked before the Swagger handler, preventing the swagger ui from showing. If this order is removed https://github.com/vaadin/flow/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletConfiguration.java#L61 the Swagger UI is shown but instead Vaadin views fail to render because of a 404

**Comment by Frettman** [comment]
@Artur-, it's what I described in detail in vaadin/spring#602 and an attempt at a solution in vaadin/spring#604.
Let's just say setting the URL mapping is much easier ;)

**Comment by Artur-** [comment]
Thanks, I was just wondering if there really is no concept of "I want to handle some of the paths that match this mapping so ask me and if I say 'no thanks', then ask the next handler". 

It sounds really impossible to be able to answer upfront "Will Vaadin handle this request" without actually letting Vaadin handle the request and see. The static cases like routes are easy, the dynamic code that you are able to add here and there is not.

**Comment by Artur-** [comment]
So if the resource handler and the Vaadin handler could be combined so that if the first returns 404, the second one is consulted then magically everything would work..

**Comment by Artur-** [comment]
This is fixed in https://github.com/vaadin/flow/pull/14579 but not in a fully automatic way. You can define paths to exclude, e.g. `vaadin.excludeUrls=/swagger-ui/**` and those will not be handled by the vaadin servlet when it is mapped to `/*`
