### ISSUE TITLE
Analyzer bower.json and webjars-bom are out of sync.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3237]
Currently we have bower.json in `flow-webcomponent-api-analyzer` that is needed for generating Java wrappers for frontend components
https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-webcomponent-api-analyzer/bower.json

We also have webjars bom that is intended to be used to fix webjars' versions so that generated Java wrappers can use the corect files
https://github.com/vaadin/flow/blob/master/webjars-bom/pom.xml

They are out of sync currently which means that we risk generating Java file that will not work with the corresponding WebJar later.

Current issues:
1. Main one: `vaadin-dialog` has different **major** versions in bom and bower.json
1. bower.json has `paper-*` elements that are not used anywhere
1. bower.json lacks some files that are present in the bom (it's fine, since some files like Grid are not autogenerated)
1. Bom has multiple transitive dependencies fixed for `vaadin-*` dependencies.
Those dependencies may be out of date, because bower dependencies have `~`, `^` magic symbols that fetch the newest transitive dependencies for `vaadin-*` dependencies – this might lead us to issues in future

We need to fix the main issue and think about the way of eliminating this error in the future.

Elimination proposal:
* move bower.json to `webjars-bom` module
* make bower.json to contain identical exactly the same dependencies as the bom file does (remove `paper-*`, add missing `vaadin-*` ones)
* basing on bower.json contents, autogenerate the bom: all we need to do is to do `bower install && bower list` and parse the output
* use flow-maven-plugin and bom in analyzer module to unpack all webjars into bower_components that is used by the analyzer to generate the metadata

**Comment by SomeoneToIgnore** [comment]
> use flow-maven-plugin and bom in analyzer module to unpack all webjars into bower_components that is used by the analyzer to generate the metadata

Alternatively, we can move the generator logic into `flow-maven-plugin` and use the plugin directly in the components, as intended.

**Comment by gilberto-torrezan** [comment]
There's one potential problem in analyzing all the files from the webjars: we don't need all the files.

The `bower.json` file is also used as a whitelist by the analyzer to know which files should be analyzed (and then Java-generated). Source: https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-webcomponent-api-analyzer/lib/js/analyzer-transform.js#L87-L91 

That's the way it is implemented now, to avoid generating anything that is not explicitly declared on the `bower.json` file.

**Comment by gilberto-torrezan** [comment]
> Alternatively, we can move the generator logic into flow-maven-plugin and use the plugin directly in the components, as intended.

That's the best solution in my opinion.

**Comment by SomeoneToIgnore** [comment]
This "best solution" requires all the other steps to be done anyway, it just eliminates the need of using the `flow-maven-plugin` in the flow itself.

Also, before moving it, we need to think of that whitelisting, since no bower.json is present for components.

**Comment by pleku** [comment]
Shouldn't the `webjars-bom` go away after https://github.com/webjars/webjars/issues/1670 is fixed and released ? So what is this optimizing for ?

**Comment by SomeoneToIgnore** [comment]
No, strictly speaking, it'll just become less bloated with duplications.
It will persist because of ranges: the resulting webJars will still have their dependencies specified in pom as a range of versions, like [1,3)

This brings two complications:
* you are not able to fix transitive dependencies without the explicit versions specified in your app or without the bom
* Maven does not treat our versions normally: 1.0.0.alpha2 **does not** belong to [1, 3) range from Maven's point of view

**Comment by pleku** [comment]
If we can't get rid of this, then I think we should move it.

Extracting the generator to the maven plugin doesn't fix the problem of things being unsync. As long as we have this `bom` in the Flow project, things will get unsync between it and the components very easily.

The sync should be enabled by the platform. Meaning that when we release a new component version and push that version to the platform, we would then have to update the version to the webjars-bom coupled with the platform releases.

Are there any technical limitations to moving these there ? Or political ? ping @Artur-

**Comment by Legioth** [comment]
I agree that the contents of the webjars BOM probably would belong in the platform instead of Flow for the simple reason that we should also make sure that a given platform version uses the same version of any transitive dependency regardless of whether you're using Maven or Bower.

In either case, there should be one single source of truth.

**Comment by SomeoneToIgnore** [comment]
> contents of the webjars BOM probably would belong in the platform instead of Flow 

Not sure that's the right thing to do:

1. I think we should concentrate on eliminating the bower.json from the project first before moving the bom anywhere (since it's the topic of the issue)
1. What about the demos and components that depend on the snapshot version of everything, including the bom? 
1. Also, we may update the bom multiple times before the next Flow release, how would we able to use it in all these project considering the fact that platform is released separately from our artifacts and there are no snapshot version of it? 
1. Now we use the bom in all components' repos to be sure that each component have WebJars and transitive dependencies exactly with the versions we want them to be (remember the ranges). And then the components are used in the platform as a dependency. If you move this bom into the Platform, you'll create a circular dependency or force everyone to fix all dependencies in each component project manually. This does not look good.

Let's consider a use case.
How adding a new component works now on ListBox example:
* add a new bower.json entry, generate new Java wrapper (Flow repo)
* add a new bom entries to fix the WebJar version and its transitive dependencies for each component (Flow repo)
* merge the changes into master so that there is a new snapshot bom with updated versions (Flow repo)
* create a new repo, adds WebJar, bom, other dependencies (component repo)
* copy paste the generated api from Flow, add other code, commit, push, release (component repo)

This particular ticket focuses on merging first two bullets into one.

There's another ticket to remove the `copy paste the generated api` step that requires moving the generator into the plugin, but it's a different story.

Anyway, if you insist on moving the bom to the platform, I suggest you to provide an updated workflow here.
We can schedule a meeting to discuss it, if that would be easier.

@ZheSun88 and @pekam may have some ideas on how to improve the situation since they are mostly working with the component repos now.

**Comment by pleku** [comment]
>I think we should concentrate on eliminating the bower.json from the project first before moving the bom anywhere (since it's the topic of the issue)

The bower.json will be eliminated when the analyzer & generator is part of the maven plugin (or somewhere else) where from it can be executed for each component individually. Doing anything else for it at this point would end up being a waste of time in my opinion.

> What about the demos and components that depend on the snapshot version of everything, including the bom?
>Now we use the bom in all components' repos to be sure that each component have WebJars and transitive dependencies exactly with the versions we want them to be (remember the ranges). And then the components are used in the platform as a dependency. If you move this bom into the Platform, you'll create a circular dependency or force everyone to fix all dependencies in each component project manually. This does not look good.

The components should be only providing the versions for the webjars that they are build on or need on the demos (latter scoped `test`). Not sure if this will even ever cause any conflict resolution to the `pom.xml` for each component. The _current_ `webjars-bom` should not IMO be used in the components as it is now for [flow-component-base](https://github.com/vaadin/flow-component-base/blob/master/pom.xml#L37).
At most it should be there for only resolving only the needed webjars for Flow. 

>Also, we may update the bom multiple times before the next Flow release, how would we able to use it in all these project considering the fact that platform is released separately from our artifacts and there are no snapshot version of it?

Which projects ? Components should not need it. Starters will need it if they are not using a fixed platform version, as they do now. Our technical demos might (?) need it but then again they can use whatever since they are not "public marketing demos".

A platform snapshot is also something that we should be getting and could help us.

**Comment by pleku** [comment]
Concluding this after some f2f discussions:

- For V10, we will move the webjars-bom dependency resolving to platform once https://github.com/webjars/webjars/issues/1670 is fixed and there is new versions released from all webjars we need. We can either create a new issue for this or use this one for that purpose.
- The platform will always have the same version of the `vaadin-element` and the matching `vaadin-element-flow`. Thus when a new element version is released, there needs to be a flow component release for that too before it is taken into the platform.
- Our Components will declare their own used webjars dependencies instead of depending on any BOM.
- For V10 add-ons made by users, they should build their add-ons depending on **some specific platform version** instead of Flow. Thus they will get the webjars dependencies from the platform-bom and have to make sure any new dependencies are aligned with that.
