### ISSUE TITLE
Importing Css files within a module of a multi-module project fails. 

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/flow#6652]
**WARNING:**: you have to run the project using IntelliJ as a Main Java class to reproduce the behavior. Also please see comments below how to fix the provided project to make it buildable. I cannot reproduce it with Eclipse.

Steps to reproduce:

Project structure (spring multi-module project):
```
* master
      * application-form-master
            * application-form-base
            * application-form-shell
      * deployments-master
            * application-form
```
`application-form` is the war module. `application-form-shell` contains css files inside `resources/META-INF/resources/frontend` and a component still inside the `application-form-shell` like this:
```
@CssImport("./styles/lumo/typography.css")
public class FlexBoxLayout extends FlexLayout {
....
```
Steps to try and run the app:
1. `mvn clean install` for the whole project
2. mvn clean install` inside the `application-form-shell` module (where the styles and the FlexBoxLayout is located)
3. Try running the app using spring application class (the one annotated with @SpringBootApplication) which is located inside the war module  `application-form`

It fails with the exception:
```
java.lang.IllegalStateException: Failed to update the Flow imports file '/Users/klau/development/projects/lotteri/sourcecode/compus2/deployments/compus-application-form/target/frontend/generated-flow-imports.js'
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:128) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:368) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:248) ~[flow-server-2.0.8.jar:2.0.8]
....
Caused by: java.lang.IllegalStateException: 

  Failed to find the following css files in the `node_modules` or `/Users/klau/development/projects/lotteri/sourcecode/compus2/deployments/compus-application-form/frontend` directory tree:
- ./styles/lumo/typography.css
Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
```

**Comment by denis-anisimov** [comment]
The description requires quite complicated setup.
Could you please provide either the projects skeletons that I may use to copy paste to see the behavior or describe step by step how I can reproduce the same project structure ?

It's not obvious that the bug is in Flow from the ticket. To be able to verify that we are on the same page I should be able to repeat your configuration exactly. I cannot do this with such description, sorry.

**Comment by Klaudeta** [comment]
Finally a simplified version of our project:

[multi-module-flow-14-master.zip](https://github.com/vaadin/flow/files/3716248/multi-module-flow-14-master.zip)

**Comment by denis-anisimov** [comment]
```
Could not resolve dependencies for project com.vaadin.multimodule:application-form-base:jar:1.0-SNAPSHOT: Could not find artifact com.vaadin.multimodule:shared-spring-support:jar:1.0-SNAPSHOT 
```

**Comment by Klaudeta** [comment]
Fixed

[multi-module-flow-14-master.zip](https://github.com/vaadin/flow/files/3716612/multi-module-flow-14-master.zip)

or
https://github.com/Klaudeta/multi-module-flow-14

**Comment by denis-anisimov** [comment]
The provided projects (neither the latest zip nor github) still don't work.

To be able to run them one should:
- Remove `ApplicationFormShellConfig` 
- remove not-existed dependency (see below) from the web project

Not existed dep:
```
        <dependency>
            <groupId>com.vaadin.multimodule</groupId>
            <artifactId>application-form-shell</artifactId>
            <version>${project.version}</version>
        </dependency>
```

Now with the fixes above I've able to run the project and everything is fine.

I don't see any error like that : `Failed to update the Flow imports file `.
There is no `styles/lumo/typography.css`  anywhere defined.
I believe the error should be caused by `styles/app.css`  , right ?
I don't see any error as I said.
And the import is in the DOM.
If  I open the inspector in the browser then I see in the `head`:

```
<custom-style><style>.just-layout {
  width: 50vw;
    height: 50vh;
}

</style></custom-style>
```

And this is exactly what should be.

Can I close this ticket as `works for me`   or you have objections ?

**Comment by Klaudeta** [comment]
You are right about the issues to run the source code. Trying to have this simple project structure as close as possible to our real project, I couldn't notice the missing dependency as they were initially installed in my local repo and `mvn clean install` kept executing normally in my local machine, so yes my bad about this.

But still after doing the above fixes that you also did above (remove the dependency and the Config class), and then run `mvn clean install` and try to run the ApplicationForm class, the error is still there.
Attached is the log file

[console.log](https://github.com/vaadin/flow/files/3716958/console.log)

**Comment by Klaudeta** [comment]
Update: yes that's true running the app through command line it  runs normally, while running the app using the application class as I've mentioned in the beginning of this issue

> 3. Try running the app using spring application class (the one annotated with @SpringBootApplication) which is located inside the war module application-form

it fails.

**Comment by denis-anisimov** [comment]
I don't use IntelliJ.
I use Eclipse.
Works in the same way: no any error .
Did you install the _WHOLE_ project before you run the main Java class from your IDE ?
As I said: the Jar project (which is a dependency) has to be installed locally as a Jar.

**Comment by Klaudeta** [comment]
Yes I did install the whole project and to remove any doubt, I just deleted the repo from my local maven and re-installed the project again. Checked that the jar are in my local maven and ran the application class from IDE. Still same issue.

**Comment by denis-anisimov** [comment]
Since there is so many misunderstandings : the jar which you mean is the `application-form-base` Jar, right ? Not the `application-form-web`  (which is also a Jar and not a WAR).

**Comment by Klaudeta** [comment]
Yes

**Comment by denis-anisimov** [comment]
OK, I'm not able to reproduce this but I have Eclipse.
I will add a comment about the way to run the project.
May be someone else with IntelliJ may reproduce it.

**Comment by Klaudeta** [comment]
The issue can be reproduced in Eclipse too:
1. Add a new dummy css file in the same style directory where app.css is
2. run `mvn clean install` on the whole project 
3. Run as Java application from IDE

The difference is that if after adding new css files and importing them,  you run the app from cmd the first time, everything works fine and it will continue to work even if you after first run in cmd,  switch to run the app from IDE.

It matters how you run the app the first time after adding new css file and importing them.

**Comment by denis-anisimov** [comment]
It's extremely hard to reproduce this bug because almost any action after you imported the project makes it unreproducible.

The bug indeed exists in `14.0.2` Platform. Which is Flow 2.0.8.
To reproduce it you have to make a fresh clone of https://github.com/Klaudeta/multi-module-flow-14 , import into IDE and run the main Java class.
If you have already this project then remove it.
Do a fresh clone as written.
Otherwise you have a chance do not reproduce.

The reason of the behavior is : the FS dependency paths in `2.0.8`  Flow are not handled anyhow.
But once you build the project the dependencies becomes binary JAR files and resources will be found in those paths without issues. So the project has to be unbuilt.

In the latest Flow there is already code which cares about FS paths. So it works already fine there.
As a result : the bug is already fixed in the latest Flow and Platform.
Just use the latest version.
