### ISSUE TITLE
OSGi is completely broken in 2.2

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#8109]
`flow-server` module has a dependency to `org.apache.httpcomponents.httpclient` which has the manifest but this manifest doesn't expose any packages for external use.
So effectively `org.apache.httpcomponents.httpclient`  is not an OSGi bundle at all (even though it's loaded by OSGi container).
It doesn't have OSGi symbolic name and apparently wasn't intended to be used in OSGi.

This is at least one problem.
There can be other problems as well. It's hard to identify all of them because one unresolved dependency has a cumulative effect : `flow-server`  can't be loaded, every bundle which depends on it can't be loaded and so on (transitive dependencies).
At the moment all Flow bundles can't be loaded because of `flow-server` : all others depend on it.
But once issue with `flow-server`  is resolved there an be other issues.

**Comment by denis-anisimov** [comment]
Dependency is introduced by the `DefaultFileDownloader` which is used to download and install `node`.

**Comment by denis-anisimov** [comment]
May be it's enough to use `httpclient-osgi` instead of `httpclient`.

**Comment by denis-anisimov** [comment]
Fixed by #8111

**Comment by caalador** [comment]
8111 didn't fix any of the tests.
`Tests failed: 261, passed: 8, ignored: 4 `

**Comment by denis-anisimov** [comment]
WTH :(
