### ISSUE TITLE
Error "Can't move a node from one state tree to another." when re-adding a previously removed component after refreshing with @PreserveOnRefresh

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#8286]
### Description of the bug

If a component is added and then removed from a component that is preserved on refresh, trying to add it again after refreshing results in the error

`java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree`

### Minimal reproducible example

Code below. Steps to reproduce:

1. Click the first button
2. Click the second button
3. Refresh the page
4. Click the first button again

---

    import com.vaadin.flow.component.Text;
    import com.vaadin.flow.component.button.Button;
    import com.vaadin.flow.component.html.Div;
    import com.vaadin.flow.component.orderedlayout.VerticalLayout;
    import com.vaadin.flow.router.PreserveOnRefresh;
    import com.vaadin.flow.router.Route;
    
    @Route("")
    @PreserveOnRefresh
    public class MainView extends VerticalLayout {
        public MainView() {
            Text text1 = new Text("Text 1");
            Text text2 = new Text("Text 2");
    
            Div container = new Div();
    
            Button button1 = new Button("Set text 1", e -> {
                container.removeAll();
                container.add(text1);
            });
            Button button2 = new Button("Set text 2", e -> {
                container.removeAll();
                container.add(text2);
            });
    
            add(button1, button2, container);
        }
    }

### Expected behavior

`Text 2` is replaced by `Text 1`.

### Actual behavior

An exception is thrown

`java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree`

### Versions:

- Vaadin 14.1.27, Flow 2.1.9
- Java version: openjdk 11.0.4
- OS version: Windows 10
- Application Server (if applicable): Spring Boot embedded Tomcat

**Comment by denis-anisimov** [comment]
Confirmed.

Thank you very much for precise and short steps to reproduce.
:+1:

**Comment by mvysny** [comment]
In which Vaadin version the fix was released please?

**Comment by joheriks** [comment]
Released in [Flow 2.2.1](https://github.com/vaadin/flow/releases/tag/2.2.1) which is included in [Vaadin 14.2.1](https://github.com/vaadin/platform/releases/tag/14.2.1).

**Comment by sandu-c** [comment]
still reproducible when using Chrome, try for example to right-click on the tab where UI is loaded and select `duplicate tab` then same exception shows up

**Comment by jhult** [comment]
I can reproduce this by duplicating the tab (per @sandu-c's instructions) or after using `Page.reload())` (using Vaadin 17 with Flow 4.0-SNAPSHOT).

This happens for me even without using `@PreserveOnRefresh`. It seems like it is caused by me for `Dialog`.

```
java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
	at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:717) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.StateNode.lambda$setTree$3(StateNode.java:370) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.StateNode$$Lambda$480/0000000000000000.accept(Unknown Source) ~[?:?]
	at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:670) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:370) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:270) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:78) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:53) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:42) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:102) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.dom.Node.insertChild(Node.java:294) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.component.HasComponents.add(HasComponents.java:53) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.component.UI.add(UI.java:999) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.component.dialog.Dialog.lambda$ensureAttached$504e9d67$1(Dialog.java:469) ~[vaadin-dialog-flow-4.0-SNAPSHOT.jar:?]
	at com.vaadin.flow.component.dialog.Dialog$$Lambda$996/0000000000000000.accept(Unknown Source) ~[?:?]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:368) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.internal.StateTree$$Lambda$715/0000000000000000.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:365) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:389) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:172) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.server.communication.UidlRequestHandler.createUidl(UidlRequestHandler.java:158) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:146) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115) ~[flow-server-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	
```

@joheriks, @denis-anisimov - any ideas?

**Comment by denis-anisimov** [comment]
This ticket was absolutely specific for `@PreserveOnRefresh`.
The reason has been identified based on provided code sample and fixed.
So this ticket is fixed and closed.

If you see another issue then please:
- create another ticket.
- provide exact steps to reproduce
- it might be that this ticket should be made in the `Dialog` repository.
