### ISSUE TITLE
[WARNING] Couldn't find  dev dependencies file. Dev dependencies won't be locked

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9251]
### Description of the bug
The warning
```
2020-10-28 11:17:03.290  INFO 37635 --- [nPool-worker-19] c.v.f.s.frontend.TaskUpdatePackages      : Running `pnpm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
2020-10-28 11:17:03.296  WARN 37635 --- [nPool-worker-19] c.v.f.s.frontend.TaskUpdatePackages      : Couldn't find  dev dependencies file. Dev dependencies won't be locked
```
is printed on every build when `pnpm` is used, e.g. any V17 build.

Please provide instructions on what to fix in the project, fix the issue in Flow or remove the warning if it has no meaning.

### Minimal reproducible example
`mvn` in any project

**Comment by caalador** [comment]
I think the ´flow-dev-deps` dependency should be added to the Platform so the dependency would come from the vaadin(-core) dependency.
@denis-anisimov could you confirm this.

**Comment by denis-anisimov** [comment]
`flow-dev-deps`  should be in the list of dependencies , yes.
The warning is shown just because the resource from this module is not available.

I don't know anything about Platform.
If something needs to be done in Platform to make it working then it should be done in the Platform: so may be it's worth to transfer the issue to the Platform?

**Comment by ZheSun88** [comment]
Adding the module into platform can fix the mentioned issue, and PR is ready vaadin/platform#1638

but it causes platform validation failure, ticket #9345

**Comment by sachinlala** [comment]
Hi @ZheSun88, @pleku:

Please can you confirm if this issue is now resolved ? Which version of vaadin should we reference ? I'm currently on `14.4.0`.

Appreciate your help.

Sachin

**Comment by ZheSun88** [comment]
Hi @sachinlala , 
Thanks for using Vaadin. We changed the log level for this message from error/warning and this fix has been included in Vaadin `14.4.4` and `17.0.11`. 

BR,
Zhe

**Comment by chkpnt** [comment]
I'm using `14.4.7` but still see 

```
> Task :webui:vaadinBuildFrontend
Couldn't find  dev dependencies file. Dev dependencies won't be locked
```

in my Gradle's output. Am I missing something?
